# Generated by Django 5.2.1 on 2025-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('testing', 'Testing'), ('ads', 'Ads')], max_length=20, null=True),
        ),
    ]
